server:
  port: 8080
spring:
 cloud:
   gateway:
     routes:
       - id: user-app
         uri: http://localhost:8083
         predicates:
           - Path=/login/**
           - Path=/user/**



       - id: order-service
         uri: lb://ORDER-SERVICE
         predicates:
           - Path=/order/**


 application:
   name: API-GATEWAY


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/